Repository knative-extensions/func-go, pull requests merged in 2023-08, with the labels that each got.

#30 feat: static config
  http/service.go
  http/service_test.go
Labels: approved, lgtm, size/L

#31 Rename knative-sandbox to knative-extensions
  go.mod
Labels: size/XS, approved, lgtm

#32 chore: use knative.dev in module name
  cmd/fce/main.go
  cmd/fhttp/main.go
  go.mod
  http/service_test.go
Labels: size/XS, approved, lgtm

#33 feat: support LISTEN_ADDRESS
  http/mock/function.go
  http/service.go
  http/service_test.go
Labels: approved, lgtm
