Repository knative-extensions/func-go, pull requests merged in 2024-02, with the labels that each got.

#47 Fix problem with binding and test for real port
  cloudevents/service.go
  cloudevents/service_test.go
Labels: approved, lgtm, size/S

#48 Adding tests for READY and ALIVE
  cloudevents/service_test.go
  http/service_test.go
Labels: approved, lgtm, size/L

#49 Adding timeout channel
  cloudevents/service_test.go
  http/service_test.go
Labels: approved, lgtm, size/S

#50 Adding matzew as approver
  OWNERS
Labels: size/XS, approved, lgtm

#51 Remove service port constant
  cloudevents/service.go
Labels: size/XS, approved, lgtm

#52 Adding timeout channel to the rest of the test suite
  cloudevents/service_test.go
  http/service_test.go
Labels: approved, lgtm, size/M

#54 [main] Update community files
  OWNERS_ALIASES
Labels: size/L, skip-review

#56 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/L, skip-review

#55 [main] Format Go code
  cloudevents/mock/function.go
  cloudevents/service_test.go
Labels: size/XS, approved, lgtm

#53 Adjusting tests, so they are more similar
  cloudevents/service_test.go
  http/service_test.go
Labels: approved, lgtm, size/L
