Repository knative-extensions/func-go, pull requests merged in 2024-03, with the labels that each got.

#57 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, skip-review

#58 Drop context arg from HTTP handler
  cloudevents/service.go
  cmd/fhttp/main.go
  http/instance.go
  http/mock/function.go
  http/service.go
  http/service_test.go
Labels: approved, lgtm, size/M

#59 update dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#60 chore: install maintenance scripts
  go.mod
  go.sum
  hack/tools.go
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  third_party/VENDOR-LICENSE/github.com/cloudevents/sdk-go/v2/LICENSE
  third_party/VENDOR-LICENSE/github.com/google/uuid/LICENSE
  third_party/VENDOR-LICENSE/github.com/json-iterator/go/LICENSE
  third_party/VENDOR-LICENSE/github.com/mattn/go-colorable/LICENSE
  third_party/VENDOR-LICENSE/github.com/mattn/go-isatty/LICENSE
  third_party/VENDOR-LICENSE/github.com/modern-go/concurrent/LICENSE
  third_party/VENDOR-LICENSE/github.com/modern-go/reflect2/LICENSE
  third_party/VENDOR-LICENSE/github.com/rs/zerolog/LICENSE
  third_party/VENDOR-LICENSE/go.uber.org/multierr/LICENSE.txt
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
  third_party/VENDOR-LICENSE/golang.org/x/sys/unix/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/func-go/LICENSE
Labels: approved, lgtm, size/XXL

#62 Support legacy static handler
  http/instance.go
  http/service.go
  http/service_test.go
Labels: approved, lgtm, size/M

#63 fix backwards compatibility
  http/instance.go
  http/service.go
Labels: approved, lgtm, size/S

#64 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#66 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#65 CE service impl. using Fprint with writer, instead of direct writer call
  cloudevents/service.go
Labels: size/XS, approved, lgtm

#67 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#69 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#70 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#68 chore: Using constants instead of hard-coded vals
  cloudevents/service.go
  http/service.go
Labels: approved, lgtm, size/S

#71 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, approved, lgtm
